name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact file
        required: true
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: Result of deployment operation
        value: ${{jobs.deploy.outputs.result_value}}
jobs:
  deploy:
    outputs:
      result_value: ${{steps.set-result_id.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: List files
        run: ls -la
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result_id
        run: echo "step-result=success" >> $GITHUB_OUTPUT
